language: node_js
branches:
    only:
        - master
cache:
    directories:
        - node_modules
notifications:
    email: false
node_js:
    - '7.5'
before_script:
    - npm prune && npm cache clean
script:
    - npm run test && npm run build
